
function(is_debug BUILD_TYPE BUILD_TYPES VARIABLE_NAME)
	list(FIND BUILD_TYPES "${BUILD_TYPE}" IS_DEBUG_INTERNAL)
	if ("${IS_DEBUG_INTERNAL}" EQUAL -1)
		set(${VARIABLE_NAME} 0 PARENT_SCOPE)
	else()
		set(${VARIABLE_NAME} 1 PARENT_SCOPE)
	endif()
endfunction(is_debug)

function(is_known BUILD_TYPE KNOWN_TYPES VARIABLE_NAME)
	list(FIND KNOWN_TYPES "${BUILD_TYPE}" IS_KNOWN_INTERNAL)
	if ("${IS_KNOWN_INTERNAL}" EQUAL -1)
		set(${VARIABLE_NAME} 0 PARENT_SCOPE)
	else()
		set(${VARIABLE_NAME} 1 PARENT_SCOPE)
	endif()
endfunction(is_known)

function(prepend_each LIST VALUE VARIABLE_NAME)
	set( RESULT )
	foreach(ITEM ${LIST})
		set(FULL_ITEM "${VALUE}/${ITEM}")
		list(APPEND RESULT "${FULL_ITEM}")
	endforeach(ITEM)
	set(${VARIABLE_NAME} ${RESULT} PARENT_SCOPE)
endfunction(prepend_each)